### ISSUE TITLE
Email notifications not work

### ISSUE THREAD

**Issue by dezzzm** [grafana/oncall#1044]
Oncall v1.1.8. Installed via helm chart.
Email notifications not work.

env example:
```
- name: FEATURE_EMAIL_INTEGRATION_ENABLED
      value: "True"
    - name: EMAIL_HOST
      value: smtp.test.com
    - name: EMAIL_PORT
      value: "465"
    - name: EMAIL_HOST_USER
      value: test@test.ru
    - name: EMAIL_HOST_PASSWORD
      valueFrom:
        secretKeyRef:
          key: smtp-password
          name: oncall-smtp
          optional: true
    - name: EMAIL_USE_TLS
      value: "True"
    - name: EMAIL_FROM_ADDRESS
      value: test@test.ru
```

Logs:
```
2022-12-26 16:37:57 | oncallgrafana/oncall:v1.1.8oncall-celery-6947cd64f7-mrg7s10.111.1.205celeryDeployment/oncall-celerystderr | 2022-12-26 09:37:57,144 source=engine:celery worker=ForkPoolWorker-3 task_id=87f5721a-15d2-471f-b238-a08cb270c89a task_name=apps.email.tasks.notify_user_async name=celery.app.trace level=INFO Task apps.email.tasks.notify_user_async[87f5721a-15d2-471f-b238-a08cb270c89a] retry: Retry in 1s: SMTPServerDisconnected('Connection unexpectedly closed: timed out')
```
