### ISSUE TITLE
Connector API for Grafana to automatically connect Grafana to the existing OnCall instance

### ISSUE THREAD

**Issue by geowatson** [grafana/oncall#122]
It would be great to automatically connect on-premise Grafana instance during upgrade (via helm etc) to the existing OnCall instance via custom env variables, or config in grafana.ini and config in oncall helm chart.

**Comment by Matvey-Kuk** [comment]
We added this task to the core team's backlog.

**Comment by DavidSpek** [comment]
I believe this could be done with a secret and the plugins sidecar already. For example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: oncall-plugin
  namespace: oncall
  labels:
    grafana_plugin: ""
type: Opaque
stringData:
  oncall-plugin.yaml: |
    apiVersion: 1
    apps:
    - type: grafana-oncall-app
      name: grafana-oncall-app
      disabled: false
      jsonData:
        grafanaUrl: https://grafana.example.com
        onCallApiUrl: https://oncall.example.com
      secureJsonData:
        onCallInvitationToken: xxxx
```

While this does configure the plugin, I'm getting an error about the token being invalid (`It seems like your invite token may be invalid.`).
