### ISSUE TITLE
[helm] external rabbitmq cluster connection

### ISSUE THREAD

**Issue by Kot-o-pes** [grafana/oncall#1323]
Hello, im installing oncall from helm and have a separate rabbitmq cluster deployed outside k8s and i cannot connect to cluster from externalRabbitmq values, only to one node 
```
rabbitmq:
  enabled: false # Disable the RabbitMQ dependency from the release

externalRabbitmq:
  host: rmqhost1, rmqhost2, rmqhost3 
  port:
  user:
  password:
  protocol:
  vhost:
  existingSecret: ""
  passwordKey: password
  usernameKey: username
  ```
  such configuration is not working, please add ability to connect to separate rmq cluster
