### ISSUE TITLE
[part:deployment/helm bug] Cannot complete helm installation - missing database password

### ISSUE THREAD

**Issue by flockoftanks** [grafana/oncall#1727]
Hey all,
- OSS
- 1.1.32

I'm trying to install grafana-oncall oss. I already have a grafana so I just want to extend the existing instance. I already have RabbitMQ so I'm just integrating into that. I use Istio so I don't need ingress or cert manager. However, I do want to use the install of a db from the chart, but I get this error every time.

![image](https://user-images.githubusercontent.com/10449510/231272325-f7300f16-08e2-49ec-921e-288a2ff167ff.png)

I get the same error for mariadb except it says "mariadb" instead of postgress. I don't know if this happened the first time I installed but I never really got this far.

I've deleted all secrets and PVCs related to this namespace and even deleted the namespace itself before running `helm install` again but I get this same error. The DB appears to be installing correctly and I CAN get the password from the `export` command in the error message, but I assumed this would configure itself.

I don't see anything in the README where I'm supposed to take that password and add it to my values.yaml anywhere.

Including my values for reference:
```
    base_url: https://oncall.grafana.domain.com
    externalGrafana:
      url: https://grafana.domain.com
    grafana:
      enabled: false
    rabbitmq:
      enabled: false
    externalRabbitmq:
      host: rabbitmq.rabbitmq.svc.cluster.local
      port: 5672
      vhost: grafana
      existingSecret: grafana-oncall-rabbitmq
      passwordKey: rabbitmq_grafana_password
      usernameKey: rabbitmq_grafana_user
    ingress:
      enabled: false
    ingress-nginx:
      enabled: false
    cert-manager:
      enabled: false
    mariadb:
      enabled: false
    postgresql:
      enabled: true
    database:
      type: postgresql
```
Thanks!
