### ISSUE TITLE
OnCall keeps getting out of sync

### ISSUE THREAD

**Issue by runderwoodcr14** [grafana/oncall#1876]
Hi everyone,

We have managed to deploy OnCall OSS in our GKE cluster, we already had Grafana so we are not using the bundled Grafana provided in the helm chart, we are also not using cert-manager from the helm chart as per already have one cert-manager operational, we are also using an existing rabbitmq and an existing redis, we are doing the deployment using ArgoCD, we manage to get the plugin configured in Grafana, however after a few hours the plugin stops working and we get this messages in the celery pod
```
oncall 2023-05-04 06:39:19,142 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.grafana_plugin.tasks.sync.plugin_sync_organization_async[b78a9fcb-cdab-43df-90ba-5ac4695b541a] received                                                                                                                     
oncall 2023-05-04 06:39:19,148 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=apps.grafana_plugin.tasks.sync level=INFO Start sync Organization 1                                                                                                     
oncall 2023-05-04 06:39:19,278 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=apps.grafana_plugin.helpers.client level=WARNING Error connecting to api instance 401 Client Error: Unauthorized for url: http://grafana.grafana.svc.cluster.local/api/access-control/users/permissions/search?actionPrefix=grafana-oncall-app                                                                                                                 
oncall 2023-05-04 06:39:19,279 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=root level=INFO outbound latency=0.030810272990493104 status=401 method=HEAD url=http://grafana.grafana.svc.cluster.local/api/access-control/users/permissions/search?actionPrefix=grafana-oncall-app slow=0                                                                                                                                                   
oncall 2023-05-04 06:39:19,296 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=apps.grafana_plugin.helpers.client level=WARNING Error connecting to api instance 401 Client Error: Unauthorized for url: http://grafana.grafana.svc.cluster.local/api/org                                                                                                                                                                                     
oncall 2023-05-04 06:39:19,297 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=root level=INFO outbound latency=0.01774857701093424 status=401 method=HEAD url=http://grafana.grafana.svc.cluster.local/api/org slow=0                                 
oncall 2023-05-04 06:39:19,302 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=apps.grafana_plugin.tasks.sync level=INFO Finish sync Organization 1                                                                                                    
oncall 2023-05-04 06:39:19,303 source=engine:celery worker=ForkPoolWorker-2 task_id=b78a9fcb-cdab-43df-90ba-5ac4695b541a task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=celery.app.trace level=INFO Task apps.grafana_plugin.tasks.sync.plugin_sync_organization_async[b78a9fcb-cdab-43df-90ba-5ac4695b541a] succeeded in 0.15628815500531346s: 
None                                                                                                                                                                                   
oncall 2023-05-04 06:40:11,889 source=engine:celery worker=Beat task_id=??? task_name=??? name=celery.beat level=INFO Scheduler: Sending due task check_escalations (apps.alerts.tasks.check_escalation_finished.check_escalation_finished_task)                                                                                                                              
oncall 2023-05-04 06:40:11,895 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.worker.strategy level=INFO Task apps.alerts.tasks.check_escalation_finished.check_escalation_finished_task[bdf98c09-09b4-4232-bcb9-1a53e44ca7a9] received                                                                                                        
oncall 2023-05-04 06:40:11,908 source=engine:celery worker=ForkPoolWorker-2 task_id=bdf98c09-09b4-4232-bcb9-1a53e44ca7a9 task_name=apps.alerts.tasks.check_escalation_finished.check_escalation_finished_task name=py.warnings level=WARNING /usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField AlertGroup.started_at received a naive datetime (2023-03-25 00:00:00) while time zone support is active.                                                                                                 
oncall   warnings.warn("DateTimeField %s received a naive datetime (%s)"                                                                                                               
oncall                                                                                                                                                                                 
oncall 2023-05-04 06:40:11,996 source=engine:celery worker=ForkPoolWorker-2 task_id=bdf98c09-09b4-4232-bcb9-1a53e44ca7a9 task_name=apps.alerts.tasks.check_escalation_finished.check_escalation_finished_task name=apps.alerts.tasks.task_logger level=INFO There are no alert groups to audit, everything is good :)
```
This is what we get from the OnCall engine itself:
```
oncall 2023-05-04 06:39:18 source=engine:app google_trace_id=none logger=root outbound latency=0.07643767300760373 status=200 method=HEAD url=http://grafana.grafana.svc.cluster.local/ api/org slow=0                                                                                                                                                                          
oncall 2023-05-04 06:39:18 source=engine:app google_trace_id=none logger=root inbound latency=0.180362 status=200 method=GET path=/api/internal/v1/plugin/status content-length=0 slow=0                                                                                                                                                                                       
oncall 2023-05-04 06:39:18 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/status latency=0.184372 google_trace_id=- protocol=HTTP/1.1 resp_size=325 req_body_size=0                                                                                                                                                                                    
oncall 2023-05-04 06:39:19 source=engine:app google_trace_id=none logger=root inbound latency=0.096438 status=202 method=POST path=/api/internal/v1/plugin/sync content-length=0 slow=0                                                                                                                                                                                       
oncall 2023-05-04 06:39:19 source=engine:uwsgi status=202 method=POST path=/api/internal/v1/plugin/sync latency=0.099445 google_trace_id=- protocol=HTTP/1.1 resp_size=278 req_body_size=0                                                                                                                                                                                     
oncall 2023-05-04 06:39:19 source=engine:app google_trace_id=none logger=root inbound latency=0.077116 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:19 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.078813 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:19 source=engine:app google_trace_id=none logger=root inbound latency=0.087833 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:19 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.090846 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:19 source=engine:app google_trace_id=none logger=root inbound latency=0.085944 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:19 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.091831 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:20 source=engine:app google_trace_id=none logger=root inbound latency=0.118884 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:20 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.120814 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:20 source=engine:app google_trace_id=none logger=root inbound latency=0.131618 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:20 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.134690 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:21 source=engine:app google_trace_id=none logger=root inbound latency=0.085228 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:21 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.086862 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:21 source=engine:app google_trace_id=none logger=root inbound latency=0.094218 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:21 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.096711 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0
oncall 2023-05-04 06:39:21 source=engine:app google_trace_id=none logger=root inbound latency=0.094218 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:21 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.096711 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:22 source=engine:app google_trace_id=none logger=root inbound latency=0.106333 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:22 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.107903 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:24 source=engine:app google_trace_id=none logger=root inbound latency=0.103049 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:24 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.105463 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:27 source=engine:app google_trace_id=none logger=root inbound latency=0.400771 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:27 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.405933 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:32 source=engine:app google_trace_id=none logger=root inbound latency=0.100079 status=200 method=GET path=/api/internal/v1/plugin/sync content-length=0 slow=0  
oncall 2023-05-04 06:39:32 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/plugin/sync latency=0.101980 google_trace_id=- protocol=HTTP/1.1 resp_size=330 req_body_size=0                                                                                                                                                                                      
oncall 2023-05-04 06:39:43 source=engine:app google_trace_id=none logger=root inbound latency=0.176668 status=200 method=GET path=/api/internal/v1/escalation_policies/num_minutes_in_window_options content-length=0 slow=0 user_id=10 org_id=1                                                                                                                               
oncall 2023-05-04 06:39:43 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/escalation_policies/num_minutes_in_window_options latency=0.179406 google_trace_id=- protocol=HTTP/1.1 resp_size=361 req_body_size=0                                                                                                                                                
oncall 2023-05-04 06:39:43 source=engine:app google_trace_id=none logger=root inbound latency=0.191201 status=200 method=OPTIONS path=/api/internal/v1/notification_policies content-length=0 slow=0 user_id=10 org_id=1                                                                                                                                                       
oncall 2023-05-04 06:39:43 source=engine:uwsgi status=200 method=OPTIONS path=/api/internal/v1/notification_policies latency=0.195452 google_trace_id=- protocol=HTTP/1.1 resp_size=1534 req_body_size=0                                                                                                                                                                       
oncall 2023-05-04 06:39:43 source=engine:app google_trace_id=none logger=root inbound latency=0.197647 status=200 method=GET path=/api/internal/v1/notification_policies/notify_by_options content-length=0 slow=0 user_id=10 org_id=1                                                                                                                                         
oncall 2023-05-04 06:39:43 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/notification_policies/notify_by_options latency=0.200685 google_trace_id=- protocol=HTTP/1.1 resp_size=785 req_body_size=0                                                                                                                                                          
oncall 2023-05-04 06:39:43 source=engine:app google_trace_id=none logger=root inbound latency=0.117148 status=200 method=OPTIONS path=/api/internal/v1/escalation_policies content-length=0 slow=0 user_id=10 org_id=1                                                                                                                                                         
oncall 2023-05-04 06:39:43 source=engine:uwsgi status=200 method=OPTIONS path=/api/internal/v1/escalation_policies latency=0.123547 google_trace_id=- protocol=HTTP/1.1 resp_size=3207 req_body_size=0
```
This is what we see in Grafana:
<img width="1182" alt="Screenshot 2023-05-04 at 08 52 13" src="https://user-images.githubusercontent.com/58430460/236131754-0f69e0b5-9c7f-4be9-9606-42d41d804ac0.png">

<img width="1200" alt="Screenshot 2023-05-04 at 08 54 48" src="https://user-images.githubusercontent.com/58430460/236131974-f6ad651a-1690-419e-b9b9-2604862dcd1c.png">

<img width="1197" alt="Screenshot 2023-05-04 at 08 55 25" src="https://user-images.githubusercontent.com/58430460/236131995-65086556-0575-437f-83a3-1edab11e4b09.png">

As I mentioned before, we configured and was working properly, then after a few hours the problem mentioned above starts to happen, as you can see I don't the option to remove the configuration and add it again, to do so, we need to manipulate the database of grafana and oncall to remove the information directly.
The API key is there and has not been changed:

<img width="1201" alt="Screenshot 2023-05-04 at 08 59 25" src="https://user-images.githubusercontent.com/58430460/236132810-1c7a0801-c551-40aa-9572-9fd9f2eb92ef.png">

Here is the values override used for the helm chart:

```yaml
# Values for configuring the deployment of Grafana OnCall

# Set the domain name Grafana OnCall will be installed on.
# If you want to install grafana as a part of this release make sure to configure grafana.grafana.ini.server.domain too
base_url: grafana-oncall.domain.com

secrets:
  # Use existing secret. (secretKey and mirageSecretKey is required)
  existingSecret: "oncall-gcp-secret"
  # the key in the secret containing secret key
  secretKey: "oncall-secret-key"
  # the key in the secret containing mirage secret key
  mirageSecretKey: "oncall-mirage-secret-key"

oncall:
  # Override default MIRAGE_CIPHER_IV (must be 16 bytes long)
  # For existing installation, this should not be changed.
  # mirageCipherIV: 1234567890abcdef
  # oncall secrets
  slack:
    # enabled enable the Slack ChatOps integration for the Oncall Engine.
    enabled: true
    # commandName sets the Slack bot slash-command
    commandName: grafana-oncall
    # clientId configures the Slack app OAuth2 client ID.
    # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Client ID
    clientId: ~
    # clientSecret configures the Slack app OAuth2 client secret.
    # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Client Secret
    clientSecret: ~
    # signingSecret configures the Slack app signature secret used to sign
    # requests comming from Slack.
    # api.slack.com/apps/<yourApp> -> Basic Information -> App Credentials -> Signing Secret
    signingSecret: ~
    # Use existing secret for clientId, clientSecret and signingSecret.
    # clientIdKey, clientSecretKey and signingSecretKey are required
    existingSecret: "oncall-slack-app-secret"
    # the key in the secret containing OAuth2 client ID
    clientIdKey: "clientId"
    # the key in the secret containing OAuth2 client secret
    clientSecretKey: "clientSecret"
    # the key in the secret containing the Slack app signature secret
    signingSecretKey: "signingSecret"
    # OnCall external URL
    redirectHost: grafana-oncall.domain.com

  smtp:
    enabled: false
    host: ~
    port: ~
    username: ~
    password: ~
    tls: ~
    fromEmail: ~

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_pool
              operator: In
              values:
                - observability-node-pool

tolerations:
  - key: "WorkloadSchedule"
    value: "allow"
    operator: "Equal"
    effect: "NoSchedule"

ingress-nginx:
  enabled: false

database:
  type: postgresql

mariadb:
  enabled: false

externalPostgresql:
  host: cloudsql-proxy.cloudsql-proxy.svc.cluster.local
  port: 5432
  db: grafana-oncall
  user: grafana-oncall
  existingSecret: oncall-gcp-secret
  # the key in the secret containing the database password
  passwordKey: postgres-password

# Grafana is included into this release for the convenience.
# It is recommended to host it separately from this release
grafana:
  enabled: false

externalGrafana:
  url: http://grafana.grafana.svc.cluster.local
cert-manager:
  enabled: false

rabbitmq:
  enabled: false # Disable the RabbitMQ dependency from the release

externalRabbitmq:
  host: grafana-oncall-rabbitmq
  port: 5672
  user: "rabbitmq"
  existingSecret: oncall-gcp-secret
  # the key in the secret containing the rabbitmq password
  passwordKey: rabbitmq-password

redis:
  enabled: false

externalRedis:
  host: grafana-oncall-redis-master
  # Chart currently not supports existing secrets here
  password: ***********************

```
Grafana OnCall Helm Chart Version: v1.2.10
Grafana OnCall Version: v1.2.15
Grafana Version: v9.4.7
Grafana OnCall Plugin Version: v1.2.18
