### ISSUE TITLE
Slack integration issue with auth_failed

### ISSUE THREAD

**Issue by dimitar-ivanov-93** [grafana/oncall#2035]
I am facing a similar issue to the ones described in [#90](https://github.com/grafana/oncall/issues/90) as well as [#668](https://github.com/grafana/oncall/issues/668). I will provide a full path of my troubleshooting as well as my configs, excluding any sensitive information, as this has been a real pain troubleshooting.

I am running an open-source Grafana v9.5.1 on an AWS EC2 virtual machine with Ubuntu 22. I am also running an open-source OnCall on another virtual machine in the same VPC, and same Security group. The Grafana configuration is as simple as:
An AWS application load balancer, forwards any traffic on port 443 to the Grafana target group on port :3000. The Grafana instance uses MySQL 8.0 AWS RDS instance as its database. The configs:

docker-compose.yaml
```
version: "3.9"

services:
  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./config/provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/dashboards:/var/lib/grafana/dashboards:ro
      - ./config/datasources:/etc/grafana/provisioning/datasources:ro
```
The relevant part of the .env file:
```
GF_SERVER_HTTP_PORT=3000
GF_SERVER_ROOT_URL=https://dash.example.com
GF_SERVER_PROTOCOL=http
GF_SERVER_DOMAIN=dash.example.com
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-oncall-app
GF_INSTALL_PLUGINS=grafana-oncall-app
GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-exampleadminpassword}
GF_DATABASE_TYPE=mysql
GF_DATABASE_HOST=grafana-rds-new.exampleurl.rds.amazonaws.com
GF_DATABASE_NAME=grafana
GF_DATABASE_USER=grafana
GF_DATABASE_PASSWORD="exampledbpassword"
```

I have a CNAME leading from dash.example.com to the external AWS ALB Grafana-Public-ALB-examplenumbers.elb.amazonaws.com
That way I am able to access my Grafana instance from the internet. 
There is also an internal AWS load balancer that also proxies traffic to the same Grafana (internal-Grafana-Private-ALB-examplenumbers.elb.amazonaws.com). Initially, it was intended to be used by Oncall to connect to Grafana, however, when I managed to set up Slack and sent a test alert, the alert links (Resolve, Acknowledge, etc.) also pointed to that same internal LB and so were inaccessible from Slack. Thus, I decided to make OnCall use the public ALB instead.

My OnCall instance (v1.2.30, also tried with a few previous versions) is similar, it has an External application load balancer, Oncall-Public-ALB-examplenumbers.elb.amazonaws.com, for the purpose of Slack talking via HTTPS to it. The OnCall then connects to the same AWS RDS instance, but to its own database, called 'oncall'. Here are the configs:
docker-compose.yaml
```
version: "3.9"

x-environment: &oncall-environment
  DATABASE_TYPE: mysql
  MYSQL_DB_NAME: $MYSQL_DB
  MYSQL_USER: $MYSQL_USER
  MYSQL_HOST: $MYSQL_HOST
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_PORT: 3306
  BROKER_TYPE: redis
  BASE_URL: $DOMAIN
  SECRET_KEY: $SECRET_KEY
  REDIS_URI: redis://redis:6379/0
  DJANGO_SETTINGS_MODULE: settings.hobby
  CELERY_WORKER_QUEUE: "default,critical,long,slack,telegram,webhook,retry,celery"
  CELERY_WORKER_CONCURRENCY: "4"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "1000"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  GRAFANA_API_URL: $GRAFANA_API_URL
  SLACK_CLIENT_OAUTH_ID: $SLACK_CLIENT_OAUTH_ID
  SLACK_CLIENT_OAUTH_SECRET: $SLACK_CLIENT_OAUTH_SECRET
  SLACK_INSTALL_RETURN_REDIRECT_HOST: $SLACK_INSTALL_RETURN_REDIRECT_HOST
  SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
  EMAIL_FROM_ADDRESS: $EMAIL_FROM_ADDRESS
  EMAIL_HOST: $EMAIL_HOST
  EMAIL_HOST_USER: $EMAIL_HOST_USER
  EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
  EMAIL_PORT: $EMAIL_PORT
  EMAIL_USE_TLS: $EMAIL_USE_TLS
  FEATURE_LIVE_SETTINGS_ENABLED: false
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca.crt

services:
  engine:
    image: grafana/oncall:v1.2.30
    restart: always
    ports:
      - "8080:8080"
    command: >
      sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    volumes:
      - ./ssl/ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  celery:
    image: grafana/oncall:v1.2.30
    restart: always
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    volumes:
      - ./ssl/ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  oncall_db_migration:
    image: grafana/oncall:v1.2.30
    command: python manage.py migrate --noinput
    environment: *oncall-environment
    volumes:
      - ./ssl/ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0.5
    restart: always
    expose:
      - 6379
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10
```

.env file
```
MYSQL_DB=oncall
MYSQL_USER=grafana
MYSQL_HOST=grafana-rds-new.exampleurl.rds.amazonaws.com
MYSQL_PASSWORD="exampledbpassword"
DOMAIN=https://oncall.example.com
SECRET_KEY=example35characterssecret
# GRAFANA_API_URL=http://internal-Grafana-Private-ALB-examplenumbers.elb.amazonaws.com
GRAFANA_API_URL=https://dash.example.com
SLACK_CLIENT_OAUTH_ID=secret
SLACK_CLIENT_OAUTH_SECRET=secret
SLACK_INSTALL_RETURN_REDIRECT_HOST=https://oncall.example.com
SLACK_SIGNING_SECRET=secret
EMAIL_FROM_ADDRESS=devops@example.com
EMAIL_HOST=secret
EMAIL_HOST_USER=secret
EMAIL_HOST_PASSWORD=secret
EMAIL_PORT=587
EMAIL_USE_TLS=true
```

I create a Slack Bot following [this](https://grafana.com/docs/oncall/latest/open-source/) guide. Wherever I need to put the OnCall URL, I put https://oncall.example.com and a custom name for the bot.

When I initialize both services, Oncall is automatically installed. I give Grafana the OnCall backend URL (I have tested both with the privateIPaddress:8080, as well as with the https://oncall.example.com) and it connects successfully. I am able to create integrations with Email and sent them out without a problem. However, when I go to OnCall Settings -> Chat Ops -> Open Slack Connection Page, it redirects me to the Slack Bot that I have created. In the URL I can see the correct redirect_url, permission set, client_id, etc. I then click Allow, and after a second it redirects me to https://oncall.example.com, which then redirects me to https://dash.example.com/a/grafana-oncall-app/chat-ops&slack_error=auth_failed.

The logs as seen from the OnCall:
```
containers-engine-1               | 2023-05-26 09:13:43 source=engine:app google_trace_id=none logger=root inbound latency=0.040003 status=200 method=GET path=/api/internal/v1/slack_channels content-length=0 slow=0 user_id=1 org_id=1
containers-engine-1               | 2023-05-26 09:13:43 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/slack_channels?search= latency=0.043356 google_trace_id=- protocol=HTTP/1.1 resp_size=293 req_body_size=0
containers-engine-1               | 2023-05-26 09:13:44 source=engine:app google_trace_id=none logger=root inbound latency=0.114016 status=200 method=GET path=/api/internal/v1/login/slack-install-free/ content-length=0 slow=0 user_id=1 org_id=1
containers-engine-1               | 2023-05-26 09:13:44 source=engine:uwsgi status=200 method=GET path=/api/internal/v1/login/slack-install-free/ latency=0.115478 google_trace_id=- protocol=HTTP/1.1 resp_size=1036 req_body_size=0
containers-engine-1               | 2023-05-26 09:13:48 source=engine:app google_trace_id=none logger=root inbound latency=0.123699 status=302 method=GET path=/api/internal/v1/complete/slack-install-free/ content-length=0 slow=0 user_id=1 org_id=1
containers-engine-1               | 2023-05-26 09:13:48 source=engine:uwsgi status=302 method=GET path=/api/internal/v1/complete/slack-install-free/?slack_login_token=SECRET_TOKEN&code=SECRET_CODE&state= latency=0.125061 google_trace_id=- protocol=HTTP/1.1 resp_size=329 req_body_size=0
```

The Grafana logs during the same operation:
```
grafana  | logger=context userId=1 orgId=1 uname=admin t=2023-05-26T09:17:44.216871067Z level=info msg="Request Completed" method=POST path=/api/plugin-proxy/grafana-oncall-app/api/internal/v1/plugin/sync status=202 remote_addr=10.172.20.229 time_ms=59 duration=59.226789ms size=67 referer="https://dash.example.com/a/grafana-oncall-app/chat-ops&slack_error=auth_failed" handler=/api/plugin-proxy/:pluginId/*
```

What is bizarre about this is that initially, I managed to make Slack connect successfully by using the Internal Load Balancer URL as GRAFANA_API_URL in the OnCall config. However, when I try using the external, it does not work. What is even more frustrating, is that when it doesn't work, I try to revert back to the internal LB, and I can't get it back to a working state, without reprovisioning the whole infrastructure along with the databases.

The steps I have taken to try to make it work are: 

1. Open the Security group for all inbound and outbound traffic.
2. Drop both Grafana and OnCall databases before changing the URL. 
3. Reprovision the whole setup, including the load balancers, databases as well as ec2 virtual machines.
4. Setting up NginX on the Grafana machine to try proxying the traffic through there instead of using the AWS-managed load balancers. 
5. Recreated the Slack Bot multiple times, in combination with reprovisioning the rest of the infrastructure. 
6. Tested using Grafana built-in database instead of MySQL. Tested using OnCall inbuilt SQLite3 db instead of MySQL. 

I just can't make it work. Any suggestions are welcome, I will test them and get back to you.
