### ISSUE TITLE
[Bug] Helm Chart renders Ingress resource with deprecated kubernetes.io/ingress.class annotation

### ISSUE THREAD

**Issue by itspngu** [grafana/oncall#2253]
When using the Helm Chart to deploy OnCall OSS, creation of the Ingress resource fails with the following error:

```
Ingress.extensions "grafana-oncall" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```

https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

Depending on the cluster's Kubernetes version, only one of the annotation or `spec.className` should be set.

```yaml
# values.yaml

ingress:
  enabled: true
  className: nginx-internal
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
        - "{{ .Values.base_url }}"
      secretName: grafana-oncall-ingress-tls
```

Versions:
- Helm Chart: `oncall-1.2.44`
- Kubernetes: `v1.26.4`
