### ISSUE TITLE
Use external redis without password and with sentinel support

### ISSUE THREAD

**Issue by slax81** [grafana/oncall#2312]
### What went wrong?

**What happened**:
  - OnCall helm chart can't work with an external Redis instance that has no authentication, also there are no options to set up sentinel configuration

**What did you expect to happen**:
  - Ability to use "" blank password when external Redis instance doesn't have authentication configured, also more options to define sentinel hosts, port, and set name (mymaster) 

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

v1.2.44

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by njohnstone2** [comment]
@slax81 have you been able to workaround this issue?

**Comment by slax81** [comment]
@njohnstone2 No, had to use redis from the chart

**Comment by rknightion** [comment]
@njohnstone2 @slax81 this worked for me (in values file) to get external redis working with elasticache (no sentinel):

```
env:
  - name: REDIS_USERNAME
    value: ""
  - name: REDIS_PASSWORD
    value: ""
  - name: REDIS_HOST
    value: "whatever.use1.cache.amazonaws.com"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PROTOCOL
    value: "redis"
```
