### ISSUE TITLE
RabbitMQ username not respected by celery deployment - HELM

### ISSUE THREAD

**Issue by wiktorkisielewski** [grafana/oncall#2328]
### What went wrong?

**Deployment (celery) do not respect the username for RabbtiMQ broker set in values**:
 Due to this fact, it is impossible to set a custom username that **Celery** will use, yet it works when there is not username specified (so it is set to default = `user`)

This is probably caused here:
https://github.com/grafana/oncall/blob/5f73af19f0b065d31e2563f1f61198b67f097ab7/helm/oncall/templates/_env.tpl#L376-L384

Maybe it should be changed:
`rabbitmq.user` -> `rabbitmq.auth.user`
I haven't test it 

as the secret referred contains:
```yaml
data:
  rabbitmq-erlang-cookie: XXX
  rabbitmq-password: XXX
 ```

### Failing
1. Start up a helm chart with rabbitmq enabled and auth values:
```yaml
rabbitmq:
  auth:
    user: "foo"
    password: "bar"
```
2. Celery pod will begin crashlooping, due to errors with AMPQ connection, logs:
```
amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
```

### Working
1. 1. Start up a helm chart with rabbitmq enabled and auth values:
```yaml
rabbitmq:
  auth:
    password: "bar"
```
2. It works

### Grafana OnCall Version

HELM: oncall-1.2.44   v1.2.44

### Product Area

Helm

### Grafana OnCall Platform?

None
