### ISSUE TITLE
Helm chart no longer creates redis-external secret

### ISSUE THREAD

**Issue by GagarinX** [grafana/oncall#2979]
### What went wrong?

**What happened**:
-
When installing grafana-oncall helm chart v1.3.35 using `externalRedis.host` and `externalRedis.password` in values, the secret containing a given redis password is not created. When upgrading from an older version, the existing secret is deleted. As a result, oncall engine cannot connect to redis.

In the `secrets.yaml` template there is a following snippet:

```
{{- if and (eq .Values.broker.type "redis") (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncall.fullname" . }}-redis-external
type: Opaque
data:
  redis-password: {{ required "externalRedis.password is required if not redis.enabled and not externalRedis.existingSecret" .Values.externalRedis.password | b64enc | quote }}
---
{{- end }}
```

In this snippet we see that the secret is only created if `broker.type` is `redis`, but as far as I can see a connection to redis is also required if `broker.type` is `rabbitmq`.

**What did you expect to happen**:
-
A secret containing external redis password should be created, containing the password provided in values.

### How do we reproduce it?

1. Install grafana-oncall helm chart 1.3.35 using `externalRedis.host` and `externalRedis.password` in values.
2. See that the secret containing redis password is not created.

### Grafana OnCall Version

1.3.35

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by lucasfcnunes** [comment]
Something similar is happening to me...

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: grafana-oncall-engine-6bd96d55cc-9gvwk
...
status:
  initContainerStatuses:
  - image: grafana/oncall:v1.3.41
    imageID: ""
    lastState: {}
    name: wait-for-db
    ready: false
    restartCount: 0
    state:
      waiting:
        message: secret "grafana-oncall-redis-external" not found
        reason: CreateContainerConfigError
```
