### ISSUE TITLE
Web version incorrectly renders alert title and message

### ISSUE THREAD

**Issue by MrEcco** [grafana/oncall#3168]
### What went wrong?

**What happened**:

Then Grafana OnCall receives alerts from alertmanager, it shows this alert in Slack and in the Web version (right in Grafana, "Home -> Alerts & IRM -> OnCall" page). For Web, I see special symbols like `&quot;` instead of `"`. This is probably because of improper HTML escaping. For Slack, the message is looks perfect.

Example:
- In Slack: `... metrics from "postgres-exporter-main" PostgreSQL ...`
- In Web: `... metrics from &quot;postgres-exporter-main&quot; PostgreSQL ...`
- In alertrule yaml document:
```yaml
groups:
  - name: postgresql
    rules:
    - alert: PostgreSQLExporting
      expr: changes(pg_exporter_last_scrape_error[15m]) > 0
      for: 3m
      labels:
        severity: critical
        kind: database
      annotations:
        title: Cannot collect metrics from "{{ $labels.release }}" PostgreSQL instance
        description: ...
```

**What did you expect to happen**:

Just a correctly rendered message in the Web version, without escaped versions of symbols instead of the symbol itself.

### How do we reproduce it?

1. Create alertrule with one or more symbols that should be escaped in the HTML. For example any of these: `&"<>`

```yaml
groups:
  - name: postgresql
    rules:
    - alert: ExampleRuleWithDetailedMessage
      expr: vector(1) > 0 # always fires
      for: 1m
      labels:
        severity: critical
      annotations:
        title: See here: "{{ $labels }}"
```

2. Use such message templating for the alertmanager integration, that collects `.annotation.title` to the title message (and/or description)

```jinja2
{{ annotations.title }}
```

3. Fire the alert

4. Check Web and Slack messages. Web version contains `&quot;` in the places where `"` should be present

### Grafana OnCall Version

1.3.43 (grafana plugin), 1.3.42 (oncall instance)

### Product Area

Alert Flow & Configuration, Other

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

### Anything else to add?

Might be related to this: https://github.com/grafana/oncall/issues/3149
