### ISSUE TITLE
[OSS] Escalation mobile push fail with "HTTP client error 403" while test notif works

### ISSUE THREAD

**Issue by bmalynovytch** [grafana/oncall#3206]
### What went wrong?

**What happened**:
- Created an alert group
- Escalation chain triggered a mobile push notification
- Timeline shows "failed to notify ... by mobile push important"
<img width="643" alt="oncall-mobile-push-failed" src="https://github.com/grafana/oncall/assets/7847492/7ae1276c-520a-40d5-8504-ecd06c3b97fd">

**What did you expect to happen**:
- Created an alert group
- Escalation chain triggered a mobile push notification
- Get notified

### How do we reproduce it?

1. Configure Grafana and OnCall OSS
2. Plug to Grafana Cloud on EU region
3. Create alert group and escalation chain to trigger mobile push notification
4. 💥 

### Grafana OnCall Version

v1.3.47 (Docker)

### Product Area

Alert Flow & Configuration, Mobile App

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

Test notifications are working properly from the user's profile, but logs are seen in "engine" while failing notifications fail in "celery".
Their might be something wrong with GRAFANA_CLOUD_ONCALL_API_URL not being properly set/used in celery, which makes it auth on the default Grafana Cloud platform instead of https://oncall-prod-eu-west-0.grafana.net/oncall as it should.

**Comment by bmalynovytch** [comment]
I also had troubles to configure GRAFANA_CLOUD_ONCALL_API_URL using env variables and needed to enable FEATURE_LIVE_SETTINGS_ENABLED.
(See #1479)

**Comment by vadimkerr** [comment]
Hi @bmalynovytch, thank you for opening an issue! I'm trying to reproduce this now, could you please tell more about how you've passed the `GRAFANA_CLOUD_ONCALL_API_URL` env variable into your deployment?

> Their might be something wrong with GRAFANA_CLOUD_ONCALL_API_URL not being properly set/used in celery, which makes it auth on the default Grafana Cloud platform instead of https://oncall-prod-eu-west-0.grafana.net/oncall as it should.

Have you passed this env variable both to `release-oncall-engine` and `release-oncall-celery` k8s deployments?

**Comment by bmalynovytch** [comment]
Sorry @vadimkerr 
I was wrong, the setting is provided using LiveSetting, not env.

**Comment by bmalynovytch** [comment]
So ... I tried providing the token twice, using LiveSettings AND env variable.
To do so, I needed to reset the token (hadn't kept a copy of the previous).
Now, notifications work properly 🤷 

I tried removing the env variable, I get the 403 error again.
The magic is the env variable which makes things work.

There seem to be a big mess with LiveSettings and env variables 😞

**Comment by vadimkerr** [comment]
Glad it's now working for you @bmalynovytch! I'll try to reproduce this and see if there's something we can do about it.

**Comment by TomasHradecky** [comment]
can you please share what exatly and how have you configured GRAFANA_CLOUD_ONCALL_API_URL ? i have oncall in k8s cluster and with all what i've tried I still have token is invalid

**Comment by TomasHradecky** [comment]
yesterday i've tried to add env on grafana instead of  oncall on woalla second clikc on connect oncall to cloud go through. So if anyone has the same issue as me try to add  this for Grafana

```
env:
  ONCALL_CLOUD_API_URL: "https://oncall-prod-eu-west-0.grafana.net/oncall/api/v1/integrations"
 
```

@bmalynovytch thanks for info, I will try it to find what is the difference between that

**Comment by Patrick-Remy** [comment]
@TomasHradecky is this how you solved it? This is currently not working for us, we still get 404 (403 if `*_CLOUD_ONCALL_API_URL` is unset) if we try to set the token via grafana admin > plugins UI

```yaml
services:
  grafana:
    environment:
      ONCALL_CLOUD_API_URL: 'https://oncall-prod-eu-west-0.grafana.net/oncall/api/v1/integrations' # we also tried without /api/v1/integrations here
  
  on-call-engine:
    environment:
      FEATURE_LIVE_SETTINGS_ENABLED: 'true' # should be default anyway
      GRAFANA_API_URL: 'http://grafana:3000' # local network url
      GRAFANA_CLOUD_ONCALL_API_URL: 'https://oncall-prod-eu-west-0.grafana.net/oncall'
      GRAFANA_CLOUD_ONCALL_TOKEN: '<our-cloud-token>'
      GRAFANA_CLOUD_NOTIFICATIONS_ENABLED: 'true'
     
```
