### ISSUE TITLE
Can't launch simple helm chart

### ISSUE THREAD

**Issue by Aangbaeck** [grafana/oncall#3481]
### What went wrong?

**What happened**:
- I'm trying to deploy a vanilla Oncall helm chart with this setup, from the examples  https://github.com/grafana/oncall/tree/dev/helm/oncall

```
base_url: oncall.mysite.com
base_url_protocol: https

database:
  type: postgresql

mariadb:
  enabled: false

postgresql:
  enabled: true

rabbitmq:
  enabled: true

redis:
  enabled: true

ingress-nginx:
  enabled: false

cert-manager:
  enabled: false

grafana:
  enabled: false

externalGrafana:
  url: https://myhostedgrafana.com/

ingress:
  enabled: false
```

**What happens**:
RabbitMQ gets this error:
```
2023-12-01 07:17:48.704903+00:00 [warning] <0.811.0> HTTP access denied: user 'user' - invalid credentials
```
PostgreSQL gets this error:
```
FATAL: password authentication failed for user "postgres"
2023-12-01 08:31:24.733 GMT [140] DETAIL: Connection matched pg_hba.conf line 1: "host all all 0.0.0.0/0 md5"
```

### How do we reproduce it?

Use my setup.

### Grafana OnCall Version

1.3.64

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

**Comment by ac4ch** [comment]
@Aangbaeck remove pvc for rabbitmq and try clean install of helm .. worked for me

**Comment by Aangbaeck** [comment]
What i did was not using the default password and instead specify the auth explicity, like:

```
rabbitmq:
  enabled: true
  auth:
    password: "apassword"
    erlangCookie: "somethingsomethingimadeup"
```

Then it worked.
