### ISSUE TITLE
Inconsitent key reference in twilio setup

### ISSUE THREAD

**Issue by lianatech-teemu-hemmila** [grafana/oncall#3592]
### What went wrong?

**What happened**:
- Tried to setup twilio integration via helm chart

**What did you expect to happen**:
- Consistent declaration of chart values when using existing secret

### How do we reproduce it?

https://github.com/grafana/oncall/blob/dev/helm/oncall/templates/_env.tpl#L127-L132

In templates:
```
{{- if .existingSecret }}
- name: TWILIO_ACCOUNT_SID
  valueFrom:
    secretKeyRef:
      name: {{ .existingSecret }}
      key: {{ required "oncall.twilio.accountSid is required if oncall.twilio.existingSecret is not empty" .accountSid | quote }}
{{- if .authTokenKey }}
- name: TWILIO_AUTH_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ .existingSecret }}
      key: {{ required "oncall.twilio.authTokenKey is required if oncall.twilio.existingSecret is not empty" .authTokenKey | quote }}
```

In values.yaml
```
    # Use existing secret for authToken, phoneNumber, verifySid, apiKeySid and apiKeySecret.
    existingSecret: ""
    # Twilio password to allow OnCall to send SMSes and make calls
    # The key in the secret containing the auth token
    authTokenKey: ""
    # The key in the secret containing the phone number
    phoneNumberKey: ""
    # The key in the secret containing verify service sid
    verifySidKey: ""
    # The key in the secret containing api key sid
    apiKeySidKey: ""
    # The key in the secret containing the api key secret
    apiKeySecretKey: ""
```

All other configuration values have separate key value pair for referencing keys in existing secret except  `accountSid`. I'm not sure if it's intentional, but it seems like inconsitent to me.

### Grafana OnCall Version

v1.3.80

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes
