### ISSUE TITLE
twilio phonenumber >13digits not usable 

### ISSUE THREAD

**Issue by daschick111** [grafana/oncall#4134]
### What went wrong?

**What happened**:
- i set up twilio with a dutch 13digit phonenumber - including country code - providided by twilio and i get this message
"Please specify a valid phone number in the following format: +XXXXXXXXXXX"

**What did you expect to happen**:
- 

### How do we reproduce it?

1. use a valid 13 digit phonenumber as twilio_number env var

### Grafana OnCall Version

v1.3.114

### Product Area

Other

### Grafana OnCall Platform?

Kubernetes

**Comment by joeyorlando** [comment]
Hi there @daschick111 👋 

In which context are you seeing this error message? The UI? Backend logs?

**Comment by daschick111** [comment]
i got that one in the ui and it does not allow me to continue
the number i used is: +3197010208XXX

**Comment by teodosii** [comment]
@daschick111 indeed the validation doesn't allow letters, only digits, maybe that should be revised. Is the X in your phone number meant to be 9 or is it just a placeholder for your numbers? If I then replace it a number instead UI will allow it

**Comment by daschick111** [comment]
No. I only X’d out the last digits in that comment. When I entered the number I had no letters in there. Am 04.04.2024 um 18:13 schrieb Rares Mardare ***@***.***>:﻿
@daschick111 indeed the validation doesn't allow letters, only digits, maybe that should be revised. Is the X in your phone number meant to be 9 or is it just a placeholder for your numbers? If I then replace it with a number instead UI will allow it

**Comment by daschick111** [comment]
i am currently using 1.3.114, OpenSource

**Comment by daschick111** [comment]
![image](https://github.com/grafana/oncall/assets/95928219/bf8b836e-8ac0-47c2-9cdd-d0913e4d82ef)

**Comment by joeyorlando** [comment]
thanks for the screenshot @daschick111, this is helpful. I'll take a deeper look into this

**Comment by joeyorlando** [comment]
how're you setting this @daschick111? via a helm chart? I'm not able to reproduce this locally. I've used the same number you provided and the validation passes.

If you're providing this value as an env variable in a helm chart, can you try wrapping it in quotes?
```
"'<your_number>'"
```

**Comment by daschick111** [comment]
what i am doing is using terraform for my installation in azure aks
i fire a helm_release resource with values like that:
```
    oncall:
      grafana.cloud.notifications.enabled: false
      twilio:
        accountSid: ${data.azurerm_key_vault_secret.twilio_account_sid.value}
        authToken: ${data.azurerm_key_vault_secret.twilio_auth_token.value}
        phoneNumber: ${data.azurerm_key_vault_secret.twilio_phonenumber.value}
```
the phonenumber is saved in an azure keyvault in this way: "<phone_number>"
will post the outcome of your suggestion
