### ISSUE TITLE
auth_token.auth Could not get user from grafana request

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/oncall#4590]
### What went wrong?

Hello,

Setup is:
Grafana v11.0.0
OnCall v1.7.2

I'm running Grafana and Prometheus locally (not in Docker) on a uBuntu VM, but want to install OnCall which I've been trying for weeks, I'm not sure if it's a bug or not.

I wonder if it's where my docker compose setup can't talk to my local Grafana /Prometheus install, I'm so confused now.  I've removed Grafana and Prometheus from my docker compose file as I don't want it running twice.   Could the docker network have issues with the local VM network.

This is the error I see when I try the plugin using http://localhost:8080

![image](https://github.com/grafana/oncall/assets/15994497/3a3a2752-df7d-4331-baf1-b77d487ae5a5)

Docker logs for Celery:

```
2024-06-26 14:31:40,140 source=engine:celery worker=ForkPoolWorker-2 task_id=0ff54e7d-f965-4f7e-ac25-0496fd69f140 task_name=apps.grafana_plugin.tasks.sync.plugin_sync_organization_async name=apps.grafana_plugin.helpers.client level=WARNING Error connecting to api instance HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/org (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160f9a7c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Docker logs for OnCall

```
2024-06-26 14:31:41 source=engine:app google_trace_id=none logger=apps.auth_token.auth Could not get user from grafana request. Context {'UserID': 1, 'UserUID': '', 'OrgID': 2, 'OrgName': 'Global_Anonymous', 'OrgRole': 'Admin', 'Login': 'admin', 'Name': '', 'Email': 'admin@localhost', 'AuthenticatedBy': '', 'ApiKeyID': 0, 'IsServiceAccount': False, 'IsGrafanaAdmin': True, 'IsAnonymous': False, 'IsDisabled': False, 'HelpFlags1': 0, 'LastSeenAt': '2024-06-26T15:29:54+01:00', 'Teams': []}
2024-06-26 14:31:41 source=engine:app google_trace_id=none logger=root inbound latency=0.018647 status=403 method=GET path=/api/internal/v1/user user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 content-length=0 slow=0
2024-06-26 14:31:41 source=engine:app google_trace_id=none logger=django.request Forbidden: /api/internal/v1/user
2024-06-26 14:31:41 source=engine:uwsgi status=403 method=GET path=/api/internal/v1/user latency=0.020668 google_trace_id=- protocol=HTTP/1.1 resp_size=295 req_body_size=0
```

Docker Compose file

```
version: "3.9"

x-environment: &oncall-environment
  DATABASE_TYPE: sqlite3
  BROKER_TYPE: redis
  BASE_URL: $DOMAIN
  SECRET_KEY: $SECRET_KEY
  FEATURE_PROMETHEUS_EXPORTER_ENABLED: ${FEATURE_PROMETHEUS_EXPORTER_ENABLED:-false}
  PROMETHEUS_EXPORTER_SECRET: ${PROMETHEUS_EXPORTER_SECRET:-}
  REDIS_URI: redis://redis:6379/0
  DJANGO_SETTINGS_MODULE: settings.hobby
  CELERY_WORKER_QUEUE: "default,critical,long,slack,telegram,webhook,retry,celery,grafana"
  CELERY_WORKER_CONCURRENCY: "1"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  GRAFANA_API_URL: http://grafana:3000

services:
  engine:
    image: grafana/oncall
    restart: always
    ports:
      - "8080:8080"
    command: sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  celery:
    image: grafana/oncall
    restart: always
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    extra_hosts:
      - "grafana:192.168.2.65"
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  oncall_db_migration:
    image: grafana/oncall
    command: python manage.py migrate --noinput
    environment: *oncall-environment
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0.5
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  grafana_data:
  prometheus_data:
  oncall_data:
  redis_data:
```

My .env

```
DOMAIN=http://192.168.2.65:8080
# Remove 'with_grafana' below if you want to use existing grafana
# Add 'with_prometheus' below to optionally enable a local prometheus for oncall metrics
COMPOSE_PROFILES=with_prometheus
COMPOSE_PROFILES=with_grafana
# to setup an auth token for prometheus exporter metrics:
PROMETHEUS_EXPORTER_SECRET=1234
# also, make sure to enable the /metrics endpoint:
FEATURE_PROMETHEUS_EXPORTER_ENABLED=True
SECRET_KEY=123
```

My host file

192.168.2.65 grafana

Prometheus.yml - added this

```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    authorization:
      credentials: 1234
    static_configs:
            - targets: ['localhost:9090', 'localhost:9115', 'host.docker.internal:8080\']
```

If there is anything I can provide or try please let me know, thanks.

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

v1.7.2

### Product Area

Other

### Grafana OnCall Platform?

None

### User's Browser?

Chrome
