### ISSUE TITLE
Create ServiceMonitor in helm chart

### ISSUE THREAD

**Issue by sturman** [grafana/oncall#4914]
### What would you like to see!

I'd like to have a possibility to create a ServiceMonitor in helm chart to scrape metrics from Grafana OnCall engine Service

### Product Area

Metrics, Helm/Kubernetes/Docker

**Comment by paltaa** [comment]
If anyone came here looking for examples, here they are:

VMServiceScrape for victoriaMetrics operator:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: oncall
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 8080
      path: "/metrics/"
      scheme: "http"
      interval: "30s" # Scrape interval (adjust as needed)
      scrapeTimeout: "10s" # Timeout for the scrape (adjust as needed)
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: engine
      app.kubernetes.io/instance: sre-oncall #here is the release name
```

Prometheus service monitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oncall
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 8080
      path: "/metrics/"
      scheme: "http"
      interval: "30s" # Scrape interval (adjust as needed)
      scrapeTimeout: "10s" # Timeout for the scrape (adjust as needed)
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: engine
      app.kubernetes.io/instance: sre-oncall # Release name
```

**Comment by tarvip** [comment]
Regarding servicemonitors and included insights dashboard. I wonder how to deal with HA setup, e.g if you have multiple engines runing then servicemonitor will collect metrics from all pods and then included dashboard is incorrect. It looks like that included dashboard assumes that there is one pod or metrics are collected via service.

**Comment by wonderphil** [comment]
Does anyone have an example of using the authtoken? and are there any constraints on what the auth token can be?

I have tried the following and am still getting 401 Unauthorized


```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oncall
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenSecret:
        name: "grafana-oncall-exporter"
        key: "exporter-secret"
      targetPort: 8080
      path: "/metrics/"
      scheme: "http"
      interval: "30s" # Scrape interval (adjust as needed)
      scrapeTimeout: "10s" # Timeout for the scrape (adjust as needed)
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: engine
      app.kubernetes.io/instance: grafana-oncall
```
