### ISSUE TITLE
[Helm] Env vars are not merged

### ISSUE THREAD

**Issue by th30nlyw4y** [grafana/oncall#518]
Hello!
I've faced the problem with merging env vars, since they're defined and rendered as a list and helm doesn't support lists merge (and most likely will never support https://github.com/helm/helm/issues/3486). 

E.g. in following config:
### values.yaml
```
  env:
    - name: GRAFANA_CLOUD_NOTIFICATIONS_ENABLED
      value: False
    - name: SEND_ANONYMOUS_USAGE_STATS
      value: False
    - name: FEATURE_TELEGRAM_INTEGRATION_ENABLED
      value: False
```
### secret.values.yaml
```
  env:
    - name: SLACK_CLIENT_OAUTH_ID
      value: "***"
    - name: SLACK_CLIENT_OAUTH_SECRET
      value: "***"
    - name: SLACK_INSTALL_RETURN_REDIRECT_HOST
      value: "***"
    - name: SLACK_SIGNING_SECRET
      value: "***"
```
After deploying using `helm upgrade -i --namespace "${NAMESPACE}" "${RELEASE}" -f values.yaml -f secret.values.yaml .` we only have secret values in deployment. I think that it's better to use smth like it is proposed [here](https://github.com/helm/helm/issues/3486#issuecomment-700365277) instead of current template
