### ISSUE TITLE
PluginAppClientSecret not set in config

### ISSUE THREAD

**Issue by Rulasmur** [grafana/oncall#5202]
### What went wrong?

**What happened**:
- Fresh install of everything, ran the curls per the README.
- /api/plugins/grafana-oncall-app/resources/plugin/status returns `PluginAppClientSecret not set in config`

**What did you expect to happen**:
- Oncall to create it's Service account

![Image](https://github.com/user-attachments/assets/2b63853d-c694-45e3-84f5-cd434d6d45aa)

### How do we reproduce it?

1. Fresh install of Grafana and oncall
2. follow README
3. Check status api

### Grafana OnCall Version

1.11.3

### Product Area

Other

### Grafana OnCall Platform?

Docker

**Comment by kosfango** [comment]
The same issue with standalone grafana latest and oncall plugin latest
`logger=plugin.grafana-oncall-app t=2024-10-23T19:36:10.084977473Z level=error msg="Error getting settings from context" error="PluginAppClientSecret not set in config"
`

**Comment by Rulasmur** [comment]
I have been able to confirm that downgrading grafana to [11.2.3](https://github.com/grafana/grafana/releases/tag/v11.2.3) fixes the issue

**Comment by daniel-boman** [comment]
This also affects existing Grafana installations recently upgraded to v11.3, rendering OnCall unable to be viewed from Grafana.

**Comment by VermiumSifell** [comment]
It looks like if I remove the service account it doesn't create a new one on Grafana v11.3. But if I downgrade to v11.2.3 is does create the service account.

I uninstalled plugin, installed it. That's how I checked this.

**Comment by bpedersen2** [comment]
see also #5100

**Comment by shawlz** [comment]
I'm running Grafana 11.4.0 and Grafana Oncall Engine 1.13.11 and Grafana OnCall App Plugin 1.13.11 and I had this same error. 

The solution in this comment [#3761](https://github.com/grafana/oncall/issues/3761#issuecomment-2334900101) worked for me

**Comment by bck01215** [comment]
> I'm running Grafana 11.4.0 and Grafana Oncall Engine 1.13.11 and Grafana OnCall App Plugin 1.13.11 and I had this same error.
> 
> The solution in this comment [#3761](https://github.com/grafana/oncall/issues/3761#issuecomment-2334900101) worked for me

Still experiencing the issue when upgrading. Running in k8s using OSS and 2 replicas

**Comment by kko72** [comment]
I ran into the same problem, and the solution is given here: [#5100](https://github.com/grafana/oncall/issues/5100#issuecomment-2515653591)
Ensuring that in the grafana.ini these feature_toggles are set:
```
[feature_toggles]
accessControlOnCall = false
enable = externalServiceAccounts
```
and that the grafana container has the following environment variable:
```
GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED=true
```
fixed it for me.

This is also what has been done in this [commit](https://github.com/grafana/oncall/commit/df6bb69d29c7c496d70aaa583a7046787dfe68bd)

**Comment by senpro-ingwersenk** [comment]
Why is it always OnCall that requires so many dumb workarounds?...

I use Kubernetes and thus configure Grafana entirely through the environment. Any alternative to putting these settings in place?

Thanks!

**Comment by zentavr** [comment]
@senpro-ingwersenk frankly speaking I prefer bitnami charts comparing to grafana's, so I managed that.
I think the approach might be similar:
- create the config map, like:
  ```
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-oncall-plugin-provisioning
    data:
      # ref.: https://github.com/grafana/oncall/issues/4829#issuecomment-2567046523
      # stackid should be set to 5 and orgid 100 for all self hosted instances
      grafana-oncall-app.yaml: |
        apiVersion: 1
        
        apps:
          - type: grafana-oncall-app
            name: grafana-oncall-app
            disabled: false
            jsonData:
              stackId: 5
              orgId: 100
              onCallApiUrl: http://grafana-oncall-engine:8080
              #grafanaUrl: http://grafana:3000
  ```
- then mount that into grafana container to `...conf/provisioning/plugins/grafana-oncall-app.yaml` with extravolumes
