### ISSUE TITLE
Homepage only shows "Ok"

### ISSUE THREAD

**Issue by anionDev** [grafana/oncall#5366]
### What went wrong?

**What happened**:

When I call the webserver (`http://[ip-address]/`) then I just get `Ok` as response-body with statuscode 200.
I have verified that this response really comes from the oncall-engine-container using Chrome and also using wget inside of the container.

**What did you expect to happen**:

When I call the webserver (`http://[ip-address]/`) then I expect to see something like the web-application like shown in the screenshot [here](https://github.com/grafana/oncall?tab=readme-ov-file#grafana-oncall).

I can reproduce this behavior even if I delete all containers, remove the volumes and restart the docker-compose-project.

### How do we reproduce it?

I just setup'ed OnCall new on my development-server using the following docker-compose-file which i basicyll got from [here](https://raw.githubusercontent.com/grafana/oncall/dev/docker-compose.yml).

```yaml
x-environment: &oncall-environment
  DATABASE_TYPE: sqlite3
  BROKER_TYPE: redis
  BASE_URL: oncall.now327.de
  SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  FEATURE_PROMETHEUS_EXPORTER_ENABLED: false
  PROMETHEUS_EXPORTER_SECRET:
  REDIS_URI: redis://oncall_redis:6379/0
  DJANGO_SETTINGS_MODULE: settings.hobby
  CELERY_WORKER_QUEUE: "default,critical,long,slack,telegram,webhook,retry,celery,grafana"
  CELERY_WORKER_CONCURRENCY: "1"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  GRAFANA_API_URL: https://monitoring.now327.de
    
services:
  oncall_engine:
    container_name: oncall_engine
    image: grafana/oncall
    ports:
      - "8080:8080"
    command: sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    volumes:
      - ./Volumes/oncall_data:/var/lib/oncall
    networks:
      - oncall_net
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      oncall_redis:
        condition: service_healthy

  oncall_celery:
    container_name: oncall_celery
    image: grafana/oncall
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    volumes:
      - ./Volumes/oncall_data:/var/lib/oncall
    networks:
      - oncall_net
    depends_on:
      oncall_db_migration:
        condition: service_completed_successfully
      oncall_redis:
        condition: service_healthy

  oncall_db_migration:
    container_name: oncall_db_migration
    image: grafana/oncall
    command: python manage.py migrate --noinput
    environment: *oncall-environment
    volumes:
      - ./Volumes/oncall_data:/var/lib/oncall
    networks:
      - oncall_net
    depends_on:
      oncall_redis:
        condition: service_healthy

  oncall_redis:
    container_name: oncall_redis
    image: redis:7.0.15
    expose:
      - 6379
    volumes:
      - ./Volumes/redis_data:/data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    networks:
      - oncall_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10

configs:
  grafana.ini:
    content: |
      [feature_toggles]
      accessControlOnCall = false

networks:
  oncall_net:
    external: true

```

### Grafana OnCall Version

latest

### Product Area

Helm/Kubernetes/Docker

### Grafana OnCall Platform?

Docker

### User's Browser?

Chrome
