### ISSUE TITLE
Slack integration with Grafana Oncall doesn't work properly - action buttons in Slack messages received via the bot don't do anything

### ISSUE THREAD

**Issue by skostov27** [grafana/oncall#5409]
### What went wrong?

**What happened**:
- I have properly integrated my Slack workspace to Grafana Oncall and receive alert messages via the bot, but the action buttons 'acknowledge' , 'resolve' , etc. in the message don't do anything when I press them. Unlike with Telegram, the action buttons in the messages work and apply the action to the alert incident 

**What did you expect to happen**:
- For the action to be properly applied to the alert incident when pressing the button in the Slack bot message of the alert

### How do we reproduce it?

Simply receive a Slack bot message for an alert then try to press an action button like 'acknowledge' - the button is 'clickable' but no action happens

### Grafana OnCall Version

v1.13.10

### Product Area

Chatops

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

I have followed the installation steps from here:

https://grafana.com/docs/oncall/latest/set-up/open-source/#slack-setup

The integration with Telegram works 100% as intended, the integration with Slack too, apart from the action buttons on each alert message

These are the env variables that I have set (both in oncall-engine and oncall-celery deployments):

```
            - name: FEATURE_TELEGRAM_INTEGRATION_ENABLED
              value: 'True'
            - name: TELEGRAM_TOKEN
              value: XXXXXXXXXXX
            - name: TELEGRAM_WEBHOOK_HOST
              value: https://oncall.opshero.net
            - name: FEATURE_SLACK_INTEGRATION_ENABLED
              value: 'True'
            - name: SLACK_CLIENT_OAUTH_ID
              value: 'XXXXXXXXXXX'
            - name: SLACK_CLIENT_OAUTH_SECRET
              value: XXXXXXXXXXX
            - name: SLACK_INSTALL_RETURN_REDIRECT_HOST
              value: https://oncall.opshero.net
            - name: SLACK_SIGNING_SECRET
              value: XXXXXXXXXXX
```

Here is a screenshot of the action buttons:

<img width="425" alt="Image" src="https://github.com/user-attachments/assets/a9bb35c5-74f3-416f-8022-655917465dfb" />

Nothing happens when I click on them

But on Telegram, the actions properly happen there:

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/6d9c2de5-905c-42c9-8ada-48de546f2166" />

<img width="415" alt="Image" src="https://github.com/user-attachments/assets/bd38d9df-0f32-4cb5-b779-db5b006595b5" />

The 'interactivity' feature in the Slack bot manifest is properly enabled, as instructed in the documentation:

```
display_information:
  name: DreamGFAIBot
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: DreamGFAIBot
    always_online: true
  shortcuts:
    - name: Add to resolution note
      type: message
      callback_id: add_resolution_note
      description: Add this message to resolution note
  slash_commands:
    - command: /escalate
      url: https://oncall.opshero.net/slack/interactive_api_endpoint/
      description: Direct page a team or user(s)
      should_escape: false
oauth_config:
  redirect_urls:
    - https://oncall.opshero.net/api/internal/v1/complete/slack-install-free/
    - https://oncall.opshero.net/api/internal/v1/complete/slack-login/
  scopes:
    user:
      - channels:read
      - identify
      - users.profile:read
      - admin.roles:write
      - admin.invites:read
      - admin.roles:read
    bot:
      - app_mentions:read
      - channels:history
      - channels:read
      - chat:write
      - chat:write.customize
      - chat:write.public
      - commands
      - files:write
      - groups:history
      - groups:read
      - im:history
      - im:read
      - im:write
      - mpim:history
      - mpim:read
      - mpim:write
      - reactions:write
      - team:read
      - usergroups:read
      - usergroups:write
      - users.profile:read
      - users:read
      - users:read.email
      - users:write
      - assistant:write
      - conversations.connect:manage
      - canvases:write
      - canvases:read
      - bookmarks:read
      - bookmarks:write
      - groups:write
      - channels:manage
      - groups:write.topic
      - incoming-webhook
      - conversations.connect:read
      - metadata.message:read
settings:
  event_subscriptions:
    request_url: https://oncall.opshero.net/slack/event_api_endpoint/
    bot_events:
      - app_home_opened
      - app_mention
      - channel_archive
      - channel_created
      - channel_deleted
      - channel_rename
      - channel_unarchive
      - member_joined_channel
      - message.channels
      - message.im
      - subteam_created
      - subteam_members_changed
      - subteam_updated
      - user_profile_changed
  interactivity:
    is_enabled: true
    request_url: https://oncall.opshero.net/slack/interactive_api_endpoint/
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```
