### ISSUE TITLE
Non-functional deployment with helm chart

### ISSUE THREAD

**Issue by maxime-sourdin** [grafana/oncall#562]
Hello,
I tried to deploy Oncall with helm chart (on a managed Kubernetes cluster, via ArgoCD), using the built-in Mysql.

I am seeing problems as the database migration jobs are not going through:

`amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.`

When I did the tests based on the provided docker-compose, I had the same problem.

Here is an extract from the values file:
```
base_url: example.com
image:
  repository: grafana/oncall
  tag: "v1.0.37"
  pullPolicy: IfNotPresent
service:
  enabled: false
  type: LoadBalancer
  port: 8080
  annotations: {}
engine:
  replicaCount: 1
  resources: {}
celery:
  replicaCount: 1
  resources: {}
oncall:
  slack:
    enabled: false
    command: ~
    clientId: ~
    clientSecret: ~
    apiToken: ~
    apiTokenCommon: ~
  telegram:
    enabled: false
    token: ~
    webhookUrl: ~
migrate:
  enabled: true
env: []
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
  tls: 
    - hosts:
        - "{{ .Values.base_url }}"
      secretName: certificate-tls
  extraPaths: []
ingress-nginx:
  enabled: false
cert-manager:
  enabled: false
  installCRDs: false
  webhook:
    timeoutSeconds: 30
    securePort: 10260
  podDnsPolicy: None
  podDnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
mariadb:
  enabled: true
  persistence:
    enabled: true
    storageClass: "csi-ssd-disk-topology"  
  auth:
    database: oncall
  primary:
    persistence:
      enabled: true
      storageClass: "csi-ssd-disk-topology"  
    extraEnvVars:
    - name: MARIADB_COLLATE
      value: utf8mb4_unicode_ci
    - name: MARIADB_CHARACTER_SET
      value: utf8mb4
  secondary:
    persistence:
      enabled: true
      storageClass: "csi-ssd-disk-topology"  
    extraEnvVars:
    - name: MARIADB_COLLATE
      value: utf8mb4_unicode_ci
    - name: MARIADB_CHARACTER_SET
      value: utf8mb4
externalMysql:
  host:
  port:
  db_name:
  user:
  password:
rabbitmq:
  enabled: true
  persistence:
    enabled: true
    storageClass: "csi-ssd-disk-topology"  
externalRabbitmq:
  host:
  port:
  user:
  password:
  protocol:
  vhost:
redis:
  enabled: true
  architecture: standalone
  replica:
    count: 1
    persistence:
      enabled: true
      storageClass: "csi-ssd-disk-topology"
  master:
    count: 1
    persistence:
      enabled: true
      storageClass: "csi-ssd-disk-topology"  
externalRedis:
  host:
  password:
grafana:
  enabled: false
  grafana.ini:
    server:
      domain: example.com
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  persistence:
    enabled: false
  plugins:
    - grafana-oncall-app
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
init:
  securityContext: {}
```

What could be the cause of this problem?
