### ISSUE TITLE
django.request Not Found: /slack/event_api_endpoint/

### ISSUE THREAD

**Issue by dinhdobathi1992** [grafana/oncall#854]
I’m working on oncall, v1.1.0, I got this error when try to press Ack  or resolved button on slack when have a notification like this  , I take a look at engine’s logs, it said .
2022-11-15 08:04:25 source=engine:app google_trace_id=none logger=django.request Not Found: /slack/event_api_endpoint/
Am I missing anything when config ? 

![image](https://user-images.githubusercontent.com/67835317/201866779-0a8faca5-418a-4772-94a8-2aa85196f0c9.png)
it seems that I cannot access this api
```
<ONCALL_ENGINE_PUBLIC_URL>/slack/event_api_endpoint/ 
```
still dont see this api on api list https://grafana.com/docs/oncall/latest/oncall-api-reference

**Comment by iskhakov** [comment]
the reason is that the slack feature was disabled it the helm chart values.
We need to either make it enabled by default or add this step to documentation
```
oncall:
  # slack configures the Grafana Oncall Slack ChatOps integration.
  slack:
    # enabled enable the Slack ChatOps integration for the Oncall Engine.
    enabled: false
              ^^^^
```
