### ISSUE TITLE
Twilio Phone verification

### ISSUE THREAD

**Issue by oldgiova** [grafana/oncall#866]
I have a Grafana Oncall OSS setup:
* helm setup with Chart `version: 1.0.12` 
* No Cloud connector configured as [requirements](https://grafana.com/docs/oncall/latest/open-source/#twilio-setup)
* Twilio configured with the required env vars:
```
TWILIO_ACCOUNT_SID
TWILIO_VERIFY_SERVICE_SID
TWILIO_API_KEY_SID
TWILIO_API_KEY_SECRET
TWILIO_NUMBER
TWILIO_AUTH_TOKEN
```

Now that I have my instance running, I can't find a way to add and verify my phone number: If I go to Oncall > Users > my user > Edit > Phone Verification
I can just see a warning banner:
> OnCall uses Grafana Cloud for SMS and phone call notifications
> Your account successfully matched, but Cloud is not connected.

I tried Grafana version both `8.5.3` and `9.2.5`

Am I missing something? How can I start to get phone alerts from Twilio?  
Unfortunately, I can't find this information in the doc.

Thanks!

**Comment by Konstantinov-Innokentii** [comment]
Hey, @oldgiova. Did you turn off GRAFANA_CLOUD_NOTIFICATIONS_ENABLED via env file, or envs tab in the oncall? (check screenshot) 
<img width="1601" alt="Screenshot 2022-11-22 at 17 51 48" src="https://user-images.githubusercontent.com/20221722/203282824-e010f871-36cb-4d13-b1db-bc159b204370.png">

**Comment by oldgiova** [comment]
Sorry about that, it was a misconfiguration with my helm environment. Now I'm able to set and verify my phone number successfully.

**Comment by paltaa** [comment]
Hey @oldgiova could you share you configuration to make Twilio work with Oncall? Did the same config, setup all the helm related Twilio variables and setup the env variable GRAFANA_CLOUD_NOTIFICATIONS_ENABLED but still cannot verify phone numbers

**Comment by oldgiova** [comment]
> Hey @oldgiova could you share you configuration to make Twilio work with Oncall? Did the same config, setup all the helm related Twilio variables and setup the env variable GRAFANA_CLOUD_NOTIFICATIONS_ENABLED but still cannot verify phone numbers

Hey @paltaa , I'm using the Helm chart, and in the values file I set:
```
oncall:
  slack:
    enabled: true
    clientId: <redacted>
    clientSecret: <redacted>

  twilio:
    accountSid: <redacted>
    authToken: <redacted>
    phoneNumber: "<redacted>"
    verifySid: <redacted>
    apiKeySecret: <redacted>

env:
  - name: GRAFANA_CLOUD_NOTIFICATIONS_ENABLED
    value: "false"
  - name: TWILIO_NUMBER
    value: "<redacted>"
```
