### ISSUE TITLE
Not work integration with alertmanager

### ISSUE THREAD

**Issue by unfeeling91** [grafana/oncall#888]
There is some problem:

I configure alert manager integration, and in the logs I see:
`ts=2022-11-22T06:12:07.052Z caller=notify.go:743 level=debug component=dispatcher receiver=grafana_oncall integration=webhook[0] msg="Notify success" attempts=1
ts=2022-11-22T06:12:11.264Z caller=notify.go:743 level=debug component=dispatcher receiver=grafana_oncall integration=webhook[0] msg="Notify success" attempts=1
ts=2022-11-22T06:12:11.264Z caller=notify.go:743 level=debug component=dispatcher receiver=grafana_oncall integration=webhook[0] msg="Notify success" attempts=1
ts=2022-11-22T06:12:11.330Z caller=notify.go:743 level=debug component=dispatcher receiver=grafana_oncall integration=webhook[0] msg="Notify success" attempts=1
ts=2022-11-22T06:12:23.351Z caller=notify.go:743 level=debug component=dispatcher receiver=grafana_oncall integration=webhook[0] msg="Notify success" attempts=1`

Some alerts in firing state.

But in not coming to alert groups on oncall plugin page, what could be the reason for it?

**Comment by Konstantinov-Innokentii** [comment]
@unfeeling91 Could you provide more details? Not a single group was generated from there alerts?

**Comment by unfeeling91** [comment]
> @unfeeling91 Could you provide more details? Not a single group was generated from there alerts?

Hi, the alerts in multiple groups, deployed via alertmanager section kube-prometheus-stack in k8s
```
  additionalPrometheusRules:
   - name: rules
     groups:
     - name: meta
         rules:
           - alert: heartbeat
             expr: vector(1)
             labels:
               severity: none
             annotations:
               description: This is heartbeat alert
               summary: Alerting Amixr
           - name: kubernetes.rules
           rules:
            - alert: KubePodCrashLooping
              expr: |
                max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job="kube-state-metrics"}[5m]) >= 1
              annotations:
                description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
                  }}) is in waiting state (reason: "CrashLoopBackOff").'
                runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
                summary: Pod is crash looping.
              for: 15m
              labels:
                severity: warning
```
